package aps;

import aps.Product;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author s156229
 */
public class MainFrame extends javax.swing.JFrame {

    public APS aps;
    private boolean firstTimePay;
    private boolean firstTimeRemove;

    /**
     * Creates new form MainFrame
     */
    public MainFrame(APS aps) {
        this.aps = aps;
        initComponents();
        try {
            listenToKeyboard();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null,
                    ex);
        }
        
        
        this.setFocusable(true);
        this.setFocusTraversalKeysEnabled(false);

        
    }
    
    public void setFirstTimePay(){
        firstTimePay = true;
    }
    
    public void setFirstTimeRemove(){
        firstTimeRemove = true;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jFrame3 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        productPriceArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        productNameArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        productQuantityArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        toPayArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        totalPriceArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jButton1Pay = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1Help = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton1Remove = new javax.swing.JButton();
        timeGreetArea = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        instructionArea = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Your receipt will be printed.");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabel2.setText("Someone will come tp help you.");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel2)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jLabel3.setText("Scan the product to remove.");

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel3)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame3Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel3)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(25000, 25000));
        setPreferredSize(new java.awt.Dimension(1080, 720));

        MainPanel.setBackground(new java.awt.Color(184, 212, 50));
        MainPanel.setMaximumSize(new java.awt.Dimension(1080, 720));
        MainPanel.setPreferredSize(new java.awt.Dimension(1080, 720));

        jPanel2.setBackground(new java.awt.Color(254, 254, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jScrollPane4.setBorder(null);

        productPriceArea.setEditable(false);
        productPriceArea.setBackground(new java.awt.Color(254, 254, 250));
        productPriceArea.setColumns(20);
        productPriceArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        productPriceArea.setLineWrap(true);
        productPriceArea.setRows(5);
        productPriceArea.setBorder(null);
        jScrollPane4.setViewportView(productPriceArea);

        jScrollPane3.setBorder(null);

        productNameArea.setEditable(false);
        productNameArea.setBackground(new java.awt.Color(254, 254, 250));
        productNameArea.setColumns(20);
        productNameArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        productNameArea.setLineWrap(true);
        productNameArea.setRows(5);
        productNameArea.setWrapStyleWord(true);
        productNameArea.setAutoscrolls(false);
        productNameArea.setBorder(null);
        jScrollPane3.setViewportView(productNameArea);

        jScrollPane2.setBorder(null);

        productQuantityArea.setEditable(false);
        productQuantityArea.setBackground(new java.awt.Color(254, 254, 250));
        productQuantityArea.setColumns(20);
        productQuantityArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        productQuantityArea.setLineWrap(true);
        productQuantityArea.setRows(5);
        productQuantityArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(productQuantityArea);

        jPanel3.setBackground(new java.awt.Color(237, 0, 140));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setWheelScrollingEnabled(false);

        toPayArea.setEditable(false);
        toPayArea.setBackground(new java.awt.Color(237, 0, 140));
        toPayArea.setColumns(20);
        toPayArea.setFont(new java.awt.Font("Monospaced", 1, 64)); // NOI18N
        toPayArea.setForeground(new java.awt.Color(254, 254, 240));
        toPayArea.setLineWrap(true);
        toPayArea.setRows(5);
        toPayArea.setText("TO PAY");
        toPayArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(toPayArea);

        jScrollPane5.setBackground(new java.awt.Color(200, 200, 200));
        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        totalPriceArea.setEditable(false);
        totalPriceArea.setBackground(new java.awt.Color(237, 0, 140));
        totalPriceArea.setColumns(20);
        totalPriceArea.setFont(new java.awt.Font("Monospaced", 1, 64)); // NOI18N
        totalPriceArea.setForeground(new java.awt.Color(254, 254, 240));
        totalPriceArea.setRows(5);
        totalPriceArea.setAutoscrolls(false);
        jScrollPane5.setViewportView(totalPriceArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(237, 0, 140));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 160));

        jButton1Pay.setBackground(new java.awt.Color(237, 0, 140));
        jButton1Pay.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jButton1Pay.setForeground(new java.awt.Color(254, 254, 250));
        jButton1Pay.setText("PAY");
        jButton1Pay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1Pay.setContentAreaFilled(false);
        jButton1Pay.setFocusable(false);
        jButton1Pay.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton1Pay.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton1Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1PayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1Pay, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1Pay, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(237, 0, 140));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 160));

        jButton1Help.setBackground(new java.awt.Color(237, 0, 140));
        jButton1Help.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jButton1Help.setForeground(new java.awt.Color(254, 254, 250));
        jButton1Help.setText("HELP");
        jButton1Help.setActionCommand("");
        jButton1Help.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1Help.setContentAreaFilled(false);
        jButton1Help.setFocusable(false);
        jButton1Help.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton1Help.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton1Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1HelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1Help, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton1Help, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(237, 0, 140));
        jPanel6.setToolTipText("");

        jButton1Remove.setBackground(new java.awt.Color(237, 0, 140));
        jButton1Remove.setFont(new java.awt.Font("Monospaced", 1, 48)); // NOI18N
        jButton1Remove.setForeground(new java.awt.Color(254, 254, 250));
        jButton1Remove.setText("REMOVE");
        jButton1Remove.setActionCommand("");
        jButton1Remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1Remove.setContentAreaFilled(false);
        jButton1Remove.setFocusable(false);
        jButton1Remove.setMaximumSize(new java.awt.Dimension(120, 120));
        jButton1Remove.setMinimumSize(new java.awt.Dimension(120, 120));
        jButton1Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton1Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        timeGreetArea.setFont(new java.awt.Font("Monospaced", 1, 80)); // NOI18N
        timeGreetArea.setForeground(new java.awt.Color(255, 255, 255));
        timeGreetArea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timeGreetArea.setText("GOOD MORNING");
        timeGreetArea.setToolTipText("");
        timeGreetArea.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel7.setBackground(new java.awt.Color(237, 0, 140));

        instructionArea.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        instructionArea.setForeground(new java.awt.Color(255, 255, 255));
        instructionArea.setText("<html> <div style=\"font-family:Monospaced; font-size: 24;\">     <h1><u>How should I use this system</u></h1>     <ol> <!-- Lijst met nummers -->         <li>Put your items on the conveyor belt one by one.             Make sure the barcodes are faced towards the sides.</li>         <li>Let the APS scan all your items for you.</li>         <li>Take the items of the conveyor belt.</li>         <li>When you want to pay, click on the button 'PAY'</li>         <li>You will get a receipt, and can pay at the paying system.</li>         <li>If you want to remove an item, click on the button 'REMOVE'. Scan the product you want to remove.</li>     </ol> </div> </html>");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionArea, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(instructionArea, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(timeGreetArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(timeGreetArea, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1942, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1RemoveActionPerformed

    private void jButton1HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1HelpActionPerformed
        jFrame2.setLocationRelativeTo(null);
        jFrame2.add(jLabel2);
        jFrame2.pack();
        jFrame2.setVisible(true);
    }//GEN-LAST:event_jButton1HelpActionPerformed

    private void jButton1PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1PayActionPerformed

        jFrame1.setLocationRelativeTo(null);
        jFrame1.add(jLabel1);
        //jFrame1.pack();
        jFrame1.setSize(180, 50);
        jFrame1.getContentPane().setBackground(Color.red);
        if ( firstTimePay ){
        jFrame1.setUndecorated(true);
        firstTimePay = false;
        }
        jFrame1.setVisible(true);
 
        Timer timer = new Timer(2000, new ActionListener() {
 
            @Override
            public void actionPerformed(ActionEvent e) {
                // Clear text or whatever you want
                jFrame1.setVisible(false);
                APS.emptyShoppingList();
            }
        });
        // start Tick-Tack
        timer.setRepeats(false);
        timer.start();
        
    }//GEN-LAST:event_jButton1PayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel instructionArea;
    private javax.swing.JButton jButton1Help;
    private javax.swing.JButton jButton1Pay;
    private javax.swing.JButton jButton1Remove;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea productNameArea;
    private javax.swing.JTextArea productPriceArea;
    private javax.swing.JTextArea productQuantityArea;
    private javax.swing.JLabel timeGreetArea;
    private javax.swing.JTextArea toPayArea;
    private javax.swing.JTextArea totalPriceArea;
    // End of variables declaration//GEN-END:variables

    public void showShoppingList(Map<Product, Integer> shoppingList) {

        String textProductName = "";
        String textProductQuantity = "";
        String textProductPrice = "";
        String textTotalPrice = aps.getTotal();

        for (Map.Entry<Product, Integer> entry
                : shoppingList.entrySet()) {
            Product p = entry.getKey();

            textProductName += p.getName() + "\n";
            textProductQuantity += entry.getValue() + "x \n";
            textProductPrice += APS.formatPrice(entry.getValue() * p.getPrice()) + "\n";
        }

        productNameArea.setText(textProductName);
        productQuantityArea.setText(textProductQuantity);
        productPriceArea.setText(textProductPrice);
        totalPriceArea.setText(textTotalPrice);

    }
    
    public void showTime(){
        String greeting;
        GregorianCalendar gc = new GregorianCalendar();
        int hour = gc.get(GregorianCalendar.HOUR_OF_DAY); 
        if (hour < 12){
            greeting = "GOOD MORNING";
        } else if (hour >= 12 && hour < 18){
            greeting = "GOOD AFTERNOON";
        } else {
            greeting = "GOOD EVENING";
        }
        timeGreetArea.setText(greeting); 
    }
    
    public void showInstruction(){
        String instruction;
        instruction = "<html> <h3> How should I use this system? </h3> <br> "
                + "<p> <ol> <li> Put all your products one by one on the conveyor belt. <br>"
                + "Make sure the barcodes are faced towards the sides of the conveyor belt. </li></ol> </p> </html>";
        //instructionArea.setText(instruction);
    }

    public void listenToKeyboard() throws IOException {
        this.addKeyListener(new KeyboardListeners(aps));
    }
    
    public void setTotalPrice(String totalPrice){
        totalPriceArea.setText(totalPrice);
    }

}
